build:
  nodes:
    zemit:
      environment:
        php:
          version: 7.4
          # @link https://pecl.php.net/
          pecl_extensions:
            - phalcon
            - redis
            - memcached
            - apcu
      dependencies:
        after:
          - composer require --dev phalcon/ide-stubs
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
          - command: phpcs-run --config phpcs.xml
checks:
  php: true
filter:
  excluded_paths:
    - 'tests/'
  dependency_paths:
    - 'vendor/'
