build:
  nodes:
    my-tests:
      environment:
        php:
          version: 7.4
          # @link https://pecl.php.net/
          pecl_extensions:
            - psr
            - phalcon
            - redis
            - memcached
            - apcu
