build:
  nodes:
    analysis:

    my-tests:
      environment:
        php:
          version: 7.4
          # @link https://pecl.php.net/
          pecl_extensions:
            - psr
            - phalcon
            - redis
            - memcached
            - apcu
      tests:
        override:
          - php-scrutinizer-run
filter:
  excluded_paths:
    - 'tests/'
  dependency_paths:
    - 'vendor/'
