build:
  nodes:
    # Edge Zemit Build
    zemit:
      resources:
        cpus: 1
      environment:
        php:
          version: 7.4
          compile_options: '--enable-sigchild --without-pear'
          # @link https://pecl.php.net/
          pecl_extensions:
            - phalcon
            - redis
            - memcached
            - apcu
          ini:
            memory_limit: -1
      dependencies:
        before:
          - pecl install phalcon
          - pecl install redis
          - pecl install memcached
          - pecl install apcu
        after:
          - composer require --dev phalcon/ide-stubs
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
          - command: phpcs-run --config phpcs.xml
      cache:
        directories:
          - ~/.composer
          - ~/.npm
          - vendor/
          - node_modules/
checks:
  php: true
filter:
  excluded_paths:
    - 'tests/'
  dependency_paths:
    - 'vendor/'
